[opener]
edit_in_tmux = [
	{ run = 'if [ -n "$TMUX" ]; then tmux new-window -c "$PWD" "$EDITOR \"$@\""; else $EDITOR "$@"; fi', block = true, desc = "Edit in Tmux Tab" }
]

[open]
rules = [
	{ mime = "*.txt", use = [ "edit_in_tmux", "reveal" ] },
	{ mime = "text/*", use = [ "edit_in_tmux", "reveal" ] },
]

[preview]
max_width = 3000
max_height = 3000
